<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('product')->insert([
            [
                'id_category' => 1,
                'name' => 'Quần lửng mặc cực cuốn',
                'describe' => 'Quần lửng nam thoải mái, phù hợp cho mọi hoạt động.',
                'price' => 200000,
                'images' => '1-1.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 50,
                'quantity_available' => 100,
            ],
            [
                'id_category' => 2,
                'name' => 'Quần jean nữ thời trang',
                'describe' => 'Quần jean nữ cao cấp, chất liệu co giãn.',
                'price' => 300000,
                'images' => '10-2.jpg',
                'category_status' => 0,
                'product_status' => 0,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 30,
                'quantity_available' => 80,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo thun basic',
                'describe' => 'Áo thun nam phong cách, chất liệu cotton thoáng mát.',
                'price' => 150000,
                'images' => '2-5.jpg',
                'category_status' => 0,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 40,
                'quantity_available' => 90,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo sơ mi công sở',
                'describe' => 'Áo sơ mi trắng, phong cách lịch lãm.',
                'price' => 220000,
                'images' => '30-5.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 60,
                'quantity_available' => 70,
            ],
            [
                'id_category' => 2,
                'name' => 'Chân váy chữ A',
                'describe' => 'Chân váy thời trang, phù hợp nhiều phong cách.',
                'price' => 280000,
                'images' => '29-4.jpg',
                'category_status' => 0,
                'product_status' => 0,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 30,
                'quantity_available' => 40,
            ],
            [
                'id_category' => 2,
                'name' => 'Áo khoác nữ',
                'describe' => 'Áo polo chất lượng cao, thoải mái cho ngày hè.',
                'price' => 250000,
                'images' => '25-5.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 70,
                'quantity_available' => 50,
            ],
            [
                'id_category' => 2,
                'name' => 'Váy công sở thanh lịch',
                'describe' => 'Váy công sở đẹp, phù hợp đi làm.',
                'price' => 500000,
                'images' => '23-1.jpg',
                'category_status' => 0,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 5,
                'quantity_available' => 30,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo khoác gió nam',
                'describe' => 'Áo khoác nhẹ nhàng, chống gió và chống nước.',
                'price' => 350000,
                'images' => '26-1.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 6,
                'quantity_available' => 90,
            ],
            [
                'id_category' => 2,
                'name' => 'Váy maxi nữ',
                'describe' => 'Váy maxi nhẹ nhàng, thoải mái cho mùa hè.',
                'price' => 450000,
                'images' => '26-3.jpg',
                'category_status' => 0,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 3,
                'quantity_available' => 40,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo hoodie nam',
                'describe' => 'Áo hoodie thoải mái, phù hợp cho mùa thu.',
                'price' => 300000,
                'images' => '6-4.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 35,
                'quantity_available' => 75,
            ],
            [
                'id_category' => 1,
                'name' => 'Quần short thể thao nam',
                'describe' => 'Quần short co giãn, thoáng mát, thích hợp thể thao.',
                'price' => 180000,
                'images' => '1-6.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 60,
                'quantity_available' => 50,
            ],
            [
                'id_category' => 2,
                'name' => 'Quần dài công sở nữ',
                'describe' => 'Quần dài thanh lịch, phù hợp cho đi làm.',
                'price' => 400000,
                'images' => '5-3.jpg',
                'category_status' => 0,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 20,
                'quantity_available' => 60,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo ba lỗ nam',
                'describe' => 'Áo ba lỗ thể thao, chất liệu cotton mát mẻ.',
                'price' => 120000,
                'images' => '28-6.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 45,
                'quantity_available' => 70,
            ],
            [
                'id_category' => 2,
                'name' => 'Set váy áo nữ công sở',
                'describe' => 'Bộ váy áo thanh lịch, phù hợp công sở.',
                'price' => 550000,
                'images' => '25-5.jpg',
                'category_status' => 0,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 25,
                'quantity_available' => 40,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo thể thao nam',
                'describe' => 'Áo thể thao chất liệu nhẹ, thoải mái vận động.',
                'price' => 210000,
                'images' => '17-1.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 55,
                'quantity_available' => 50,
            ],
            [
                'id_category' => 2,
                'name' => 'Áo khoác nữ',
                'describe' => 'Áo khoác nữ nhẹ, phong cách cá tính.',
                'price' => 300000,
                'images' => '25-2.jpg',
                'category_status' => 0,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 30,
                'quantity_available' => 60,
            ],
            [
                'id_category' => 2,
                'name' => 'Áo hoodie nữ phong cách',
                'describe' => 'Áo hoodie nữ phong cách, phù hợp nhiều dịp.',
                'price' => 290000,
                'images' => '27-3.jpg',
                'category_status' => 1,
                'product_status' => 1,
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 40,
                'quantity_available' => 90,
            ],
        ]);
    }

}
