<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('product')->insert([
            [
                'id_category' => 1,
                'name' => 'Áo sơ mi nam',
                'describe' => 'Áo sơ mi nam cao cấp, chất liệu vải cotton',
                'price' => 200000,
                'images' => 'shirt.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 50,
                'quantity_available' => 100,
            ],
            [
                'id_category' => 2,
                'name' => 'Quần jean nữ',
                'describe' => 'Quần jean nữ, thời trang cao cấp',
                'price' => 300000,
                'images' => 'jeans.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 30,
                'quantity_available' => 80,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo thun nam',
                'describe' => 'Áo thun nam phong cách, chất liệu vải co giãn',
                'price' => 150000,
                'images' => 'tshirt.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 40,
                'quantity_available' => 90,
            ],
            [
                'id_category' => 3,
                'name' => 'Váy nữ',
                'describe' => 'Váy nữ dễ thương, phù hợp cho mùa hè',
                'price' => 250000,
                'images' => 'dress.jpg',
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 20,
                'quantity_available' => 70,
            ],
            [
                'id_category' => 4,
                'name' => 'Giày thể thao nam',
                'describe' => 'Giày thể thao nam phong cách, dễ phối đồ',
                'price' => 500000,
                'images' => 'sneakers.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 60,
                'quantity_available' => 120,
            ],
            [
                'id_category' => 2,
                'name' => 'Quần tây nam',
                'describe' => 'Quần tây nam lịch sự, phù hợp cho công sở',
                'price' => 350000,
                'images' => 'pants.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 25,
                'quantity_available' => 60,
            ],
            [
                'id_category' => 3,
                'name' => 'Chân váy nữ',
                'describe' => 'Chân váy nữ, thời trang hiện đại',
                'price' => 200000,
                'images' => 'skirt.jpg',
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 15,
                'quantity_available' => 50,
            ],
            [
                'id_category' => 4,
                'name' => 'Giày cao gót nữ',
                'describe' => 'Giày cao gót nữ sang trọng',
                'price' => 400000,
                'images' => 'heels.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 35,
                'quantity_available' => 70,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo khoác nam',
                'describe' => 'Áo khoác nam chống gió, thích hợp cho mùa đông',
                'price' => 600000,
                'images' => 'jacket.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 20,
                'quantity_available' => 80,
            ],
            [
                'id_category' => 3,
                'name' => 'Đầm dạ hội nữ',
                'describe' => 'Đầm dạ hội nữ sang trọng, lộng lẫy',
                'price' => 800000,
                'images' => 'gown.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 10,
                'quantity_available' => 30,
            ],
            [
                'id_category' => 2,
                'name' => 'Quần short nam',
                'describe' => 'Quần short nam thời trang',
                'price' => 150000,
                'images' => 'shorts.jpg',
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 18,
                'quantity_available' => 40,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo hoodie nam',
                'describe' => 'Áo hoodie nam, phong cách trẻ trung',
                'price' => 300000,
                'images' => 'hoodie.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 22,
                'quantity_available' => 55,
            ],
            [
                'id_category' => 4,
                'name' => 'Dép sandal nữ',
                'describe' => 'Dép sandal nữ tiện lợi, thoáng mát',
                'price' => 120000,
                'images' => 'sandals.jpg',
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 35,
                'quantity_available' => 60,
            ],
            [
                'id_category' => 2,
                'name' => 'Quần legging nữ',
                'describe' => 'Quần legging nữ co giãn tốt',
                'price' => 180000,
                'images' => 'leggings.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 50,
                'quantity_available' => 90,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo len nữ',
                'describe' => 'Áo len nữ ấm áp, phù hợp mùa đông',
                'price' => 250000,
                'images' => 'sweater.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 27,
                'quantity_available' => 70,
            ],
            [
                'id_category' => 3,
                'name' => 'Váy maxi nữ',
                'describe' => 'Váy maxi nữ thời trang, phong cách boho',
                'price' => 350000,
                'images' => 'maxi.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 40,
                'quantity_available' => 100,
            ],
            [
                'id_category' => 2,
                'name' => 'Quần jogger nam',
                'describe' => 'Quần jogger nam thoải mái, thời trang',
                'price' => 220000,
                'images' => 'joggers.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 45,
                'quantity_available' => 90,
            ],
            [
                'id_category' => 4,
                'name' => 'Giày lười nam',
                'describe' => 'Giày lười nam tiện dụng',
                'price' => 280000,
                'images' => 'loafers.jpg',
                'hot' => 0,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 38,
                'quantity_available' => 75,
            ],
            [
                'id_category' => 3,
                'name' => 'Đầm suông nữ',
                'describe' => 'Đầm suông nữ phong cách hiện đại',
                'price' => 320000,
                'images' => 'shift_dress.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 0,
                'number_of_purchases' => 32,
                'quantity_available' => 60,
            ],
            [
                'id_category' => 1,
                'name' => 'Áo vest nam',
                'describe' => 'Áo vest nam lịch lãm, sang trọng',
                'price' => 700000,
                'images' => 'blazer.jpg',
                'hot' => 1,
                'is_active' => 1,
                'sale' => 1,
                'number_of_purchases' => 15,
                'quantity_available' => 40,
            ],
        ]);
    }
}
